Missing RAILS_ENV=production for `rake secret`
If your're omitting RAILS_ENV you'll have:

~~~
rake aborted!                             
NameError: uninitialized constant Annotate
[…]
~~~